package life.majiang.community.model;

public class Batch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.goodsname
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.goodsnum
     *
     * @mbg.generated
     */
    private Integer goodsnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.timefinish
     *
     * @mbg.generated
     */
    private String timefinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.timeprotect
     *
     * @mbg.generated
     */
    private String timeprotect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.person
     *
     * @mbg.generated
     */
    private Integer person;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.id
     *
     * @return the value of batch.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.id
     *
     * @param id the value for batch.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.goodsname
     *
     * @return the value of batch.goodsname
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.goodsname
     *
     * @param goodsname the value for batch.goodsname
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.goodsnum
     *
     * @return the value of batch.goodsnum
     *
     * @mbg.generated
     */
    public Integer getGoodsnum() {
        return goodsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.goodsnum
     *
     * @param goodsnum the value for batch.goodsnum
     *
     * @mbg.generated
     */
    public void setGoodsnum(Integer goodsnum) {
        this.goodsnum = goodsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.timefinish
     *
     * @return the value of batch.timefinish
     *
     * @mbg.generated
     */
    public String getTimefinish() {
        return timefinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.timefinish
     *
     * @param timefinish the value for batch.timefinish
     *
     * @mbg.generated
     */
    public void setTimefinish(String timefinish) {
        this.timefinish = timefinish == null ? null : timefinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.timeprotect
     *
     * @return the value of batch.timeprotect
     *
     * @mbg.generated
     */
    public String getTimeprotect() {
        return timeprotect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.timeprotect
     *
     * @param timeprotect the value for batch.timeprotect
     *
     * @mbg.generated
     */
    public void setTimeprotect(String timeprotect) {
        this.timeprotect = timeprotect == null ? null : timeprotect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.person
     *
     * @return the value of batch.person
     *
     * @mbg.generated
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.person
     *
     * @param person the value for batch.person
     *
     * @mbg.generated
     */
    public void setPerson(Integer person) {
        this.person = person;
    }
}