package life.majiang.community.model;

public class Custom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOM.ID
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOM.NAME
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOM.TELEPHONE
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOM.TYPE
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOM.COUNT
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOM.HANDLER
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    private String handler;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOM.ID
     *
     * @return the value of CUSTOM.ID
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOM.ID
     *
     * @param id the value for CUSTOM.ID
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOM.NAME
     *
     * @return the value of CUSTOM.NAME
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOM.NAME
     *
     * @param name the value for CUSTOM.NAME
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOM.TELEPHONE
     *
     * @return the value of CUSTOM.TELEPHONE
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOM.TELEPHONE
     *
     * @param telephone the value for CUSTOM.TELEPHONE
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOM.TYPE
     *
     * @return the value of CUSTOM.TYPE
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOM.TYPE
     *
     * @param type the value for CUSTOM.TYPE
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOM.COUNT
     *
     * @return the value of CUSTOM.COUNT
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOM.COUNT
     *
     * @param count the value for CUSTOM.COUNT
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOM.HANDLER
     *
     * @return the value of CUSTOM.HANDLER
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOM.HANDLER
     *
     * @param handler the value for CUSTOM.HANDLER
     *
     * @mbg.generated Tue Dec 03 09:18:02 GMT+08:00 2019
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }
}