package life.majiang.community.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.factory
     *
     * @mbg.generated
     */
    private Integer factory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.leader
     *
     * @mbg.generated
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.leader_number
     *
     * @mbg.generated
     */
    private String leaderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.factory
     *
     * @return the value of department.factory
     *
     * @mbg.generated
     */
    public Integer getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.factory
     *
     * @param factory the value for department.factory
     *
     * @mbg.generated
     */
    public void setFactory(Integer factory) {
        this.factory = factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.leader
     *
     * @return the value of department.leader
     *
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.leader
     *
     * @param leader the value for department.leader
     *
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.leader_number
     *
     * @return the value of department.leader_number
     *
     * @mbg.generated
     */
    public String getLeaderNumber() {
        return leaderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.leader_number
     *
     * @param leaderNumber the value for department.leader_number
     *
     * @mbg.generated
     */
    public void setLeaderNumber(String leaderNumber) {
        this.leaderNumber = leaderNumber == null ? null : leaderNumber.trim();
    }
}