package life.majiang.community.model;

public class Factory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.id
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.name
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.address
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.leader
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.leader_phone
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    private String leaderPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.id
     *
     * @return the value of factory.id
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.id
     *
     * @param id the value for factory.id
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.name
     *
     * @return the value of factory.name
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.name
     *
     * @param name the value for factory.name
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.address
     *
     * @return the value of factory.address
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.address
     *
     * @param address the value for factory.address
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.leader
     *
     * @return the value of factory.leader
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.leader
     *
     * @param leader the value for factory.leader
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.leader_phone
     *
     * @return the value of factory.leader_phone
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public String getLeaderPhone() {
        return leaderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.leader_phone
     *
     * @param leaderPhone the value for factory.leader_phone
     *
     * @mbg.generated Thu Dec 05 11:02:47 CST 2019
     */
    public void setLeaderPhone(String leaderPhone) {
        this.leaderPhone = leaderPhone == null ? null : leaderPhone.trim();
    }
}