package life.majiang.community.model;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.department
     *
     * @mbg.generated
     */
    private Integer department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.timein
     *
     * @mbg.generated
     */
    private String timein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.pay
     *
     * @mbg.generated
     */
    private Integer pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.person
     *
     * @mbg.generated
     */
    private Integer person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.gender
     *
     * @return the value of manager.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.gender
     *
     * @param gender the value for manager.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.department
     *
     * @return the value of manager.department
     *
     * @mbg.generated
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.department
     *
     * @param department the value for manager.department
     *
     * @mbg.generated
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.timein
     *
     * @return the value of manager.timein
     *
     * @mbg.generated
     */
    public String getTimein() {
        return timein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.timein
     *
     * @param timein the value for manager.timein
     *
     * @mbg.generated
     */
    public void setTimein(String timein) {
        this.timein = timein == null ? null : timein.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.pay
     *
     * @return the value of manager.pay
     *
     * @mbg.generated
     */
    public Integer getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.pay
     *
     * @param pay the value for manager.pay
     *
     * @mbg.generated
     */
    public void setPay(Integer pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.phone
     *
     * @return the value of manager.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.phone
     *
     * @param phone the value for manager.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.person
     *
     * @return the value of manager.person
     *
     * @mbg.generated
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.person
     *
     * @param person the value for manager.person
     *
     * @mbg.generated
     */
    public void setPerson(Integer person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.name
     *
     * @return the value of manager.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.name
     *
     * @param name the value for manager.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.position
     *
     * @return the value of manager.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.position
     *
     * @param position the value for manager.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}