package life.majiang.community.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomIsNull() {
            addCriterion("custom is null");
            return (Criteria) this;
        }

        public Criteria andCustomIsNotNull() {
            addCriterion("custom is not null");
            return (Criteria) this;
        }

        public Criteria andCustomEqualTo(Integer value) {
            addCriterion("custom =", value, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomNotEqualTo(Integer value) {
            addCriterion("custom <>", value, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomGreaterThan(Integer value) {
            addCriterion("custom >", value, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomGreaterThanOrEqualTo(Integer value) {
            addCriterion("custom >=", value, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomLessThan(Integer value) {
            addCriterion("custom <", value, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomLessThanOrEqualTo(Integer value) {
            addCriterion("custom <=", value, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomIn(List<Integer> values) {
            addCriterion("custom in", values, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomNotIn(List<Integer> values) {
            addCriterion("custom not in", values, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomBetween(Integer value1, Integer value2) {
            addCriterion("custom between", value1, value2, "custom");
            return (Criteria) this;
        }

        public Criteria andCustomNotBetween(Integer value1, Integer value2) {
            addCriterion("custom not between", value1, value2, "custom");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andGoodsIsNull() {
            addCriterion("goods is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIsNotNull() {
            addCriterion("goods is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsEqualTo(Integer value) {
            addCriterion("goods =", value, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsNotEqualTo(Integer value) {
            addCriterion("goods <>", value, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsGreaterThan(Integer value) {
            addCriterion("goods >", value, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods >=", value, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsLessThan(Integer value) {
            addCriterion("goods <", value, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsLessThanOrEqualTo(Integer value) {
            addCriterion("goods <=", value, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsIn(List<Integer> values) {
            addCriterion("goods in", values, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsNotIn(List<Integer> values) {
            addCriterion("goods not in", values, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsBetween(Integer value1, Integer value2) {
            addCriterion("goods between", value1, value2, "goods");
            return (Criteria) this;
        }

        public Criteria andGoodsNotBetween(Integer value1, Integer value2) {
            addCriterion("goods not between", value1, value2, "goods");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(String value) {
            addCriterion("order_date =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(String value) {
            addCriterion("order_date <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(String value) {
            addCriterion("order_date >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(String value) {
            addCriterion("order_date >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(String value) {
            addCriterion("order_date <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(String value) {
            addCriterion("order_date <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLike(String value) {
            addCriterion("order_date like", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotLike(String value) {
            addCriterion("order_date not like", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<String> values) {
            addCriterion("order_date in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<String> values) {
            addCriterion("order_date not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(String value1, String value2) {
            addCriterion("order_date between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(String value1, String value2) {
            addCriterion("order_date not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andPickDateIsNull() {
            addCriterion("pick_date is null");
            return (Criteria) this;
        }

        public Criteria andPickDateIsNotNull() {
            addCriterion("pick_date is not null");
            return (Criteria) this;
        }

        public Criteria andPickDateEqualTo(String value) {
            addCriterion("pick_date =", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateNotEqualTo(String value) {
            addCriterion("pick_date <>", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateGreaterThan(String value) {
            addCriterion("pick_date >", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateGreaterThanOrEqualTo(String value) {
            addCriterion("pick_date >=", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateLessThan(String value) {
            addCriterion("pick_date <", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateLessThanOrEqualTo(String value) {
            addCriterion("pick_date <=", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateLike(String value) {
            addCriterion("pick_date like", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateNotLike(String value) {
            addCriterion("pick_date not like", value, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateIn(List<String> values) {
            addCriterion("pick_date in", values, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateNotIn(List<String> values) {
            addCriterion("pick_date not in", values, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateBetween(String value1, String value2) {
            addCriterion("pick_date between", value1, value2, "pickDate");
            return (Criteria) this;
        }

        public Criteria andPickDateNotBetween(String value1, String value2) {
            addCriterion("pick_date not between", value1, value2, "pickDate");
            return (Criteria) this;
        }

        public Criteria andHandlerIsNull() {
            addCriterion("handler is null");
            return (Criteria) this;
        }

        public Criteria andHandlerIsNotNull() {
            addCriterion("handler is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerEqualTo(Integer value) {
            addCriterion("handler =", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotEqualTo(Integer value) {
            addCriterion("handler <>", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerGreaterThan(Integer value) {
            addCriterion("handler >", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerGreaterThanOrEqualTo(Integer value) {
            addCriterion("handler >=", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLessThan(Integer value) {
            addCriterion("handler <", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLessThanOrEqualTo(Integer value) {
            addCriterion("handler <=", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerIn(List<Integer> values) {
            addCriterion("handler in", values, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotIn(List<Integer> values) {
            addCriterion("handler not in", values, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerBetween(Integer value1, Integer value2) {
            addCriterion("handler between", value1, value2, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotBetween(Integer value1, Integer value2) {
            addCriterion("handler not between", value1, value2, "handler");
            return (Criteria) this;
        }

        public Criteria andTotalCostIsNull() {
            addCriterion("total_cost is null");
            return (Criteria) this;
        }

        public Criteria andTotalCostIsNotNull() {
            addCriterion("total_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCostEqualTo(BigDecimal value) {
            addCriterion("total_cost =", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotEqualTo(BigDecimal value) {
            addCriterion("total_cost <>", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostGreaterThan(BigDecimal value) {
            addCriterion("total_cost >", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_cost >=", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostLessThan(BigDecimal value) {
            addCriterion("total_cost <", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_cost <=", value, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostIn(List<BigDecimal> values) {
            addCriterion("total_cost in", values, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotIn(List<BigDecimal> values) {
            addCriterion("total_cost not in", values, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_cost between", value1, value2, "totalCost");
            return (Criteria) this;
        }

        public Criteria andTotalCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_cost not between", value1, value2, "totalCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostIsNull() {
            addCriterion("discount_cost is null");
            return (Criteria) this;
        }

        public Criteria andDiscountCostIsNotNull() {
            addCriterion("discount_cost is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountCostEqualTo(BigDecimal value) {
            addCriterion("discount_cost =", value, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostNotEqualTo(BigDecimal value) {
            addCriterion("discount_cost <>", value, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostGreaterThan(BigDecimal value) {
            addCriterion("discount_cost >", value, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_cost >=", value, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostLessThan(BigDecimal value) {
            addCriterion("discount_cost <", value, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_cost <=", value, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostIn(List<BigDecimal> values) {
            addCriterion("discount_cost in", values, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostNotIn(List<BigDecimal> values) {
            addCriterion("discount_cost not in", values, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_cost between", value1, value2, "discountCost");
            return (Criteria) this;
        }

        public Criteria andDiscountCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_cost not between", value1, value2, "discountCost");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyIsNull() {
            addCriterion("paid_money is null");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyIsNotNull() {
            addCriterion("paid_money is not null");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyEqualTo(BigDecimal value) {
            addCriterion("paid_money =", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotEqualTo(BigDecimal value) {
            addCriterion("paid_money <>", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyGreaterThan(BigDecimal value) {
            addCriterion("paid_money >", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_money >=", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyLessThan(BigDecimal value) {
            addCriterion("paid_money <", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_money <=", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyIn(List<BigDecimal> values) {
            addCriterion("paid_money in", values, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotIn(List<BigDecimal> values) {
            addCriterion("paid_money not in", values, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_money between", value1, value2, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_money not between", value1, value2, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andWillDateIsNull() {
            addCriterion("will_date is null");
            return (Criteria) this;
        }

        public Criteria andWillDateIsNotNull() {
            addCriterion("will_date is not null");
            return (Criteria) this;
        }

        public Criteria andWillDateEqualTo(String value) {
            addCriterion("will_date =", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateNotEqualTo(String value) {
            addCriterion("will_date <>", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateGreaterThan(String value) {
            addCriterion("will_date >", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateGreaterThanOrEqualTo(String value) {
            addCriterion("will_date >=", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateLessThan(String value) {
            addCriterion("will_date <", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateLessThanOrEqualTo(String value) {
            addCriterion("will_date <=", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateLike(String value) {
            addCriterion("will_date like", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateNotLike(String value) {
            addCriterion("will_date not like", value, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateIn(List<String> values) {
            addCriterion("will_date in", values, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateNotIn(List<String> values) {
            addCriterion("will_date not in", values, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateBetween(String value1, String value2) {
            addCriterion("will_date between", value1, value2, "willDate");
            return (Criteria) this;
        }

        public Criteria andWillDateNotBetween(String value1, String value2) {
            addCriterion("will_date not between", value1, value2, "willDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateIsNull() {
            addCriterion("final_date is null");
            return (Criteria) this;
        }

        public Criteria andFinalDateIsNotNull() {
            addCriterion("final_date is not null");
            return (Criteria) this;
        }

        public Criteria andFinalDateEqualTo(String value) {
            addCriterion("final_date =", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateNotEqualTo(String value) {
            addCriterion("final_date <>", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateGreaterThan(String value) {
            addCriterion("final_date >", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateGreaterThanOrEqualTo(String value) {
            addCriterion("final_date >=", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateLessThan(String value) {
            addCriterion("final_date <", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateLessThanOrEqualTo(String value) {
            addCriterion("final_date <=", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateLike(String value) {
            addCriterion("final_date like", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateNotLike(String value) {
            addCriterion("final_date not like", value, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateIn(List<String> values) {
            addCriterion("final_date in", values, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateNotIn(List<String> values) {
            addCriterion("final_date not in", values, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateBetween(String value1, String value2) {
            addCriterion("final_date between", value1, value2, "finalDate");
            return (Criteria) this;
        }

        public Criteria andFinalDateNotBetween(String value1, String value2) {
            addCriterion("final_date not between", value1, value2, "finalDate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBackDateIsNull() {
            addCriterion("back_date is null");
            return (Criteria) this;
        }

        public Criteria andBackDateIsNotNull() {
            addCriterion("back_date is not null");
            return (Criteria) this;
        }

        public Criteria andBackDateEqualTo(String value) {
            addCriterion("back_date =", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotEqualTo(String value) {
            addCriterion("back_date <>", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateGreaterThan(String value) {
            addCriterion("back_date >", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateGreaterThanOrEqualTo(String value) {
            addCriterion("back_date >=", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateLessThan(String value) {
            addCriterion("back_date <", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateLessThanOrEqualTo(String value) {
            addCriterion("back_date <=", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateLike(String value) {
            addCriterion("back_date like", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotLike(String value) {
            addCriterion("back_date not like", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateIn(List<String> values) {
            addCriterion("back_date in", values, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotIn(List<String> values) {
            addCriterion("back_date not in", values, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateBetween(String value1, String value2) {
            addCriterion("back_date between", value1, value2, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotBetween(String value1, String value2) {
            addCriterion("back_date not between", value1, value2, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateIsNull() {
            addCriterion("back_agree_date is null");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateIsNotNull() {
            addCriterion("back_agree_date is not null");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateEqualTo(String value) {
            addCriterion("back_agree_date =", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateNotEqualTo(String value) {
            addCriterion("back_agree_date <>", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateGreaterThan(String value) {
            addCriterion("back_agree_date >", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateGreaterThanOrEqualTo(String value) {
            addCriterion("back_agree_date >=", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateLessThan(String value) {
            addCriterion("back_agree_date <", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateLessThanOrEqualTo(String value) {
            addCriterion("back_agree_date <=", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateLike(String value) {
            addCriterion("back_agree_date like", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateNotLike(String value) {
            addCriterion("back_agree_date not like", value, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateIn(List<String> values) {
            addCriterion("back_agree_date in", values, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateNotIn(List<String> values) {
            addCriterion("back_agree_date not in", values, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateBetween(String value1, String value2) {
            addCriterion("back_agree_date between", value1, value2, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackAgreeDateNotBetween(String value1, String value2) {
            addCriterion("back_agree_date not between", value1, value2, "backAgreeDate");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolIsNull() {
            addCriterion("back_money_symbol is null");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolIsNotNull() {
            addCriterion("back_money_symbol is not null");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolEqualTo(Integer value) {
            addCriterion("back_money_symbol =", value, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolNotEqualTo(Integer value) {
            addCriterion("back_money_symbol <>", value, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolGreaterThan(Integer value) {
            addCriterion("back_money_symbol >", value, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolGreaterThanOrEqualTo(Integer value) {
            addCriterion("back_money_symbol >=", value, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolLessThan(Integer value) {
            addCriterion("back_money_symbol <", value, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolLessThanOrEqualTo(Integer value) {
            addCriterion("back_money_symbol <=", value, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolIn(List<Integer> values) {
            addCriterion("back_money_symbol in", values, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolNotIn(List<Integer> values) {
            addCriterion("back_money_symbol not in", values, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolBetween(Integer value1, Integer value2) {
            addCriterion("back_money_symbol between", value1, value2, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneySymbolNotBetween(Integer value1, Integer value2) {
            addCriterion("back_money_symbol not between", value1, value2, "backMoneySymbol");
            return (Criteria) this;
        }

        public Criteria andBackMoneyIsNull() {
            addCriterion("back_money is null");
            return (Criteria) this;
        }

        public Criteria andBackMoneyIsNotNull() {
            addCriterion("back_money is not null");
            return (Criteria) this;
        }

        public Criteria andBackMoneyEqualTo(BigDecimal value) {
            addCriterion("back_money =", value, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyNotEqualTo(BigDecimal value) {
            addCriterion("back_money <>", value, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyGreaterThan(BigDecimal value) {
            addCriterion("back_money >", value, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("back_money >=", value, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyLessThan(BigDecimal value) {
            addCriterion("back_money <", value, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("back_money <=", value, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyIn(List<BigDecimal> values) {
            addCriterion("back_money in", values, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyNotIn(List<BigDecimal> values) {
            addCriterion("back_money not in", values, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("back_money between", value1, value2, "backMoney");
            return (Criteria) this;
        }

        public Criteria andBackMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("back_money not between", value1, value2, "backMoney");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_collection
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}