package life.majiang.community.model;

public class Outbound {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.timeout
     *
     * @mbg.generated
     */
    private String timeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.materialid
     *
     * @mbg.generated
     */
    private Integer materialid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound.id
     *
     * @return the value of outbound.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound.id
     *
     * @param id the value for outbound.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound.num
     *
     * @return the value of outbound.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound.num
     *
     * @param num the value for outbound.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound.timeout
     *
     * @return the value of outbound.timeout
     *
     * @mbg.generated
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound.timeout
     *
     * @param timeout the value for outbound.timeout
     *
     * @mbg.generated
     */
    public void setTimeout(String timeout) {
        this.timeout = timeout == null ? null : timeout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound.materialid
     *
     * @return the value of outbound.materialid
     *
     * @mbg.generated
     */
    public Integer getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound.materialid
     *
     * @param materialid the value for outbound.materialid
     *
     * @mbg.generated
     */
    public void setMaterialid(Integer materialid) {
        this.materialid = materialid;
    }
}