package life.majiang.community.model;

public class Productionplan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.timecreate
     *
     * @mbg.generated
     */
    private String timecreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.neednum
     *
     * @mbg.generated
     */
    private Integer neednum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.timelastest
     *
     * @mbg.generated
     */
    private String timelastest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.timeproduce
     *
     * @mbg.generated
     */
    private String timeproduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.person
     *
     * @mbg.generated
     */
    private Integer person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productionplan.goodsid
     *
     * @mbg.generated
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.id
     *
     * @return the value of productionplan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.id
     *
     * @param id the value for productionplan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.timecreate
     *
     * @return the value of productionplan.timecreate
     *
     * @mbg.generated
     */
    public String getTimecreate() {
        return timecreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.timecreate
     *
     * @param timecreate the value for productionplan.timecreate
     *
     * @mbg.generated
     */
    public void setTimecreate(String timecreate) {
        this.timecreate = timecreate == null ? null : timecreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.neednum
     *
     * @return the value of productionplan.neednum
     *
     * @mbg.generated
     */
    public Integer getNeednum() {
        return neednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.neednum
     *
     * @param neednum the value for productionplan.neednum
     *
     * @mbg.generated
     */
    public void setNeednum(Integer neednum) {
        this.neednum = neednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.timelastest
     *
     * @return the value of productionplan.timelastest
     *
     * @mbg.generated
     */
    public String getTimelastest() {
        return timelastest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.timelastest
     *
     * @param timelastest the value for productionplan.timelastest
     *
     * @mbg.generated
     */
    public void setTimelastest(String timelastest) {
        this.timelastest = timelastest == null ? null : timelastest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.state
     *
     * @return the value of productionplan.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.state
     *
     * @param state the value for productionplan.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.timeproduce
     *
     * @return the value of productionplan.timeproduce
     *
     * @mbg.generated
     */
    public String getTimeproduce() {
        return timeproduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.timeproduce
     *
     * @param timeproduce the value for productionplan.timeproduce
     *
     * @mbg.generated
     */
    public void setTimeproduce(String timeproduce) {
        this.timeproduce = timeproduce == null ? null : timeproduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.person
     *
     * @return the value of productionplan.person
     *
     * @mbg.generated
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.person
     *
     * @param person the value for productionplan.person
     *
     * @mbg.generated
     */
    public void setPerson(Integer person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productionplan.goodsid
     *
     * @return the value of productionplan.goodsid
     *
     * @mbg.generated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productionplan.goodsid
     *
     * @param goodsid the value for productionplan.goodsid
     *
     * @mbg.generated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}