package life.majiang.community.model;

public class Round {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.goods
     *
     * @mbg.generated
     */
    private Integer goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.production_plan
     *
     * @mbg.generated
     */
    private Integer productionPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.team
     *
     * @mbg.generated
     */
    private Integer team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.handler
     *
     * @mbg.generated
     */
    private Integer handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.id
     *
     * @return the value of round.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.id
     *
     * @param id the value for round.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.name
     *
     * @return the value of round.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.name
     *
     * @param name the value for round.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.goods
     *
     * @return the value of round.goods
     *
     * @mbg.generated
     */
    public Integer getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.goods
     *
     * @param goods the value for round.goods
     *
     * @mbg.generated
     */
    public void setGoods(Integer goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.count
     *
     * @return the value of round.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.count
     *
     * @param count the value for round.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.production_plan
     *
     * @return the value of round.production_plan
     *
     * @mbg.generated
     */
    public Integer getProductionPlan() {
        return productionPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.production_plan
     *
     * @param productionPlan the value for round.production_plan
     *
     * @mbg.generated
     */
    public void setProductionPlan(Integer productionPlan) {
        this.productionPlan = productionPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.team
     *
     * @return the value of round.team
     *
     * @mbg.generated
     */
    public Integer getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.team
     *
     * @param team the value for round.team
     *
     * @mbg.generated
     */
    public void setTeam(Integer team) {
        this.team = team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.handler
     *
     * @return the value of round.handler
     *
     * @mbg.generated
     */
    public Integer getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.handler
     *
     * @param handler the value for round.handler
     *
     * @mbg.generated
     */
    public void setHandler(Integer handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.introduction
     *
     * @return the value of round.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.introduction
     *
     * @param introduction the value for round.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round.state
     *
     * @return the value of round.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round.state
     *
     * @param state the value for round.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}