package life.majiang.community.model;

public class RoundMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round_material.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round_material.round
     *
     * @mbg.generated
     */
    private Integer round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round_material.material
     *
     * @mbg.generated
     */
    private Integer material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round_material.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column round_material.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round_material.id
     *
     * @return the value of round_material.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round_material.id
     *
     * @param id the value for round_material.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round_material.round
     *
     * @return the value of round_material.round
     *
     * @mbg.generated
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round_material.round
     *
     * @param round the value for round_material.round
     *
     * @mbg.generated
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round_material.material
     *
     * @return the value of round_material.material
     *
     * @mbg.generated
     */
    public Integer getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round_material.material
     *
     * @param material the value for round_material.material
     *
     * @mbg.generated
     */
    public void setMaterial(Integer material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round_material.count
     *
     * @return the value of round_material.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round_material.count
     *
     * @param count the value for round_material.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column round_material.note
     *
     * @return the value of round_material.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column round_material.note
     *
     * @param note the value for round_material.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}