package life.majiang.community.model;

public class Unqualified {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.producing
     *
     * @mbg.generated
     */
    private Integer producing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.way
     *
     * @mbg.generated
     */
    private String way;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.handler
     *
     * @mbg.generated
     */
    private Integer handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.is_handle
     *
     * @mbg.generated
     */
    private Integer isHandle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualified.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.id
     *
     * @return the value of unqualified.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.id
     *
     * @param id the value for unqualified.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.producing
     *
     * @return the value of unqualified.producing
     *
     * @mbg.generated
     */
    public Integer getProducing() {
        return producing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.producing
     *
     * @param producing the value for unqualified.producing
     *
     * @mbg.generated
     */
    public void setProducing(Integer producing) {
        this.producing = producing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.way
     *
     * @return the value of unqualified.way
     *
     * @mbg.generated
     */
    public String getWay() {
        return way;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.way
     *
     * @param way the value for unqualified.way
     *
     * @mbg.generated
     */
    public void setWay(String way) {
        this.way = way == null ? null : way.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.handler
     *
     * @return the value of unqualified.handler
     *
     * @mbg.generated
     */
    public Integer getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.handler
     *
     * @param handler the value for unqualified.handler
     *
     * @mbg.generated
     */
    public void setHandler(Integer handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.is_handle
     *
     * @return the value of unqualified.is_handle
     *
     * @mbg.generated
     */
    public Integer getIsHandle() {
        return isHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.is_handle
     *
     * @param isHandle the value for unqualified.is_handle
     *
     * @mbg.generated
     */
    public void setIsHandle(Integer isHandle) {
        this.isHandle = isHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.note
     *
     * @return the value of unqualified.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.note
     *
     * @param note the value for unqualified.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualified.state
     *
     * @return the value of unqualified.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualified.state
     *
     * @param state the value for unqualified.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}