package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Order;
import life.majiang.community.model.OrderExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    List<Order> selectByExampleWithRowbounds(OrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_collection
     *
     * @mbg.generated Wed Dec 04 21:48:20 GMT+08:00 2019
     */
    int updateByPrimaryKey(Order record);
}