package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Productionplan;
import life.majiang.community.model.ProductionplanExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductionplanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    long countByExample(ProductionplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int deleteByExample(ProductionplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int insert(Productionplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int insertSelective(Productionplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    List<Productionplan> selectByExampleWithRowbounds(ProductionplanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    List<Productionplan> selectByExample(ProductionplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    Productionplan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Productionplan record, @Param("example") ProductionplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int updateByExample(@Param("record") Productionplan record, @Param("example") ProductionplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int updateByPrimaryKeySelective(Productionplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productionplan
     *
     * @mbg.generated Thu Dec 05 11:21:39 CST 2019
     */
    int updateByPrimaryKey(Productionplan record);
}