package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Role_permission;
import life.majiang.community.model.Role_permissionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Role_permissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    long countByExample(Role_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int deleteByExample(Role_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int insert(Role_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int insertSelective(Role_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    List<Role_permission> selectByExampleWithRowbounds(Role_permissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    List<Role_permission> selectByExample(Role_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    Role_permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role_permission record, @Param("example") Role_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int updateByExample(@Param("record") Role_permission record, @Param("example") Role_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int updateByPrimaryKeySelective(Role_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Tue Dec 03 11:42:06 CST 2019
     */
    int updateByPrimaryKey(Role_permission record);
}