package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.RoundMaterial;
import life.majiang.community.model.RoundMaterialExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RoundMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    long countByExample(RoundMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int deleteByExample(RoundMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int insert(RoundMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int insertSelective(RoundMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    List<RoundMaterial> selectByExampleWithRowbounds(RoundMaterialExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    List<RoundMaterial> selectByExample(RoundMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    RoundMaterial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoundMaterial record, @Param("example") RoundMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoundMaterial record, @Param("example") RoundMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoundMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoundMaterial record);
}