package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Unqualified;
import life.majiang.community.model.UnqualifiedExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UnqualifiedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    long countByExample(UnqualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int deleteByExample(UnqualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int insert(Unqualified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int insertSelective(Unqualified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    List<Unqualified> selectByExampleWithRowbounds(UnqualifiedExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    List<Unqualified> selectByExample(UnqualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    Unqualified selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Unqualified record, @Param("example") UnqualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Unqualified record, @Param("example") UnqualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Unqualified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualified
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Unqualified record);
}