package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.User_user;
import life.majiang.community.model.User_userExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface User_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    long countByExample(User_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int deleteByExample(User_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int insert(User_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int insertSelective(User_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    List<User_user> selectByExampleWithRowbounds(User_userExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    List<User_user> selectByExample(User_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    User_user selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") User_user record, @Param("example") User_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int updateByExample(@Param("record") User_user record, @Param("example") User_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int updateByPrimaryKeySelective(User_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbg.generated Tue Dec 03 09:50:33 CST 2019
     */
    int updateByPrimaryKey(User_user record);
}